export const SELECT_POD = 'SELECT_POD';
export const NEXT_POD = 'NEXT_POD';
export const PREVIOUS_POD = 'PREVIOUS_POD';
export const FETCH_PODS_FAILURE = 'FETCH_PODS_FAILURE';
export const FETCH_PODS_SUCCESS = 'FETCH_PODS_SUCCESS';
export const POST_LIKE_PODS_FAILURE = 'POST_LIKE_PODS_FAILURE';
export const POST_LIKE_PODS_SUCCESS = 'POST_LIKE_PODS_SUCCESS';
