const playlist = [{
  _id: '5aa24b9fa2b049090fca1dc6',
  title: 'The Official Vue News',
  link: 'http://news.vuejs.org',
  description: 'We cover the latest Vue news and tutorials in about 5 minutes.  Our goal is to give you the information you need to stay on top of your game as a Vue developer.  Links to all the stories we talk about can be found in our weekly newsletter and on http://news.vuejs.org\n',
  image: 'https://images.fireside.fm/podcasts/images/a/a16d96ec-7315-4f65-b85c-41ace3e84c7e/cover.jpg',
  author: 'Vue Mastery',
  episodeTitle: '#84 - March 6, 2018',
  episodeDescription: 'Vue.js Amsterdam Videos &amp; Photos, Storefront 1.0RC, Nuxt v1.4.0, Quasar v0.15.6, Building a Custom Router, Chat with Evan You, Tips for vue-analytics, Accessible Autocomplete, SASS in Nuxt, Vue Animations with Sketch + Haiku, and Show/Hide password in Vue. \n',
  published: '2018-03-06T15:30:00.000Z',
  url: 'https://aphid.fireside.fm/d/1437767933/a16d96ec-7315-4f65-b85c-41ace3e84c7e/c73d7cf5-0518-435c-965e-03d7a8c48631.mp3',
  mediaType: '0',
  likes: 0,
}, {
  _id: '5aa24be5a2b049090fca2009',
  title: 'The Web Ahead',
  link: 'http://5by5.tv/webahead',
  description: 'Conversations with world experts on changing technologies and future of the web. The Web Ahead is your shortcut to keeping up. Hosted by Jen Simmons.',
  image: 'http://icebox.5by5.tv/images/broadcasts/26/cover.jpg',
  author: '5by5',
  episodeTitle: '47: Jen Robbins',
  episodeDescription: "Jen Robbins  joins Eric Meyer and Jen Simmons for another episode in The Web Behind series. They talk about the early days of web design, O'Reilly, GNN, wrestling with technology and more.\n",
  published: '2013-01-16T00:15:00.000Z',
  url: 'http://fdlyr.co/d/webahead/cdn.5by5.tv/audio/broadcasts/webahead/2013/webahead-047.mp3',
  mediaType: '0',
  likes: 0,
}, {
  _id: '5aa24a14a2b049090fca1b3f',
  title: 'All JavaScript Podcasts by Devchat.tv',
  link: 'http://devchat.tv',
  description: 'All JavaScript Shows published by Devchat.tv',
  image: 'https://s3.amazonaws.com/devchat.tv/MasterJSFeed.jpg',
  author: 'Devchat.tv',
  copyright: '2011-2017 Intentional Excellence Productions, LLC',
  episodeTitle: 'MJS #001: Keith Horwood',
  episodeDescription: '<p><span style="font-family:georgia,serif"><span style="font-size:14px">On today&#39;s episode of My JS Story, Charles Max Wood welcomes Keith Horwood. Keith was previously on ep 220 of Jabbascript Jabber talking about Nodal. On this, the first episode of My JS Story, we&#39;ll find out more about Keith and what makes him tick as a programmer. Tune in to&nbsp;<strong>MJS #001: Keith Horwood</strong>.</span></span></p>\r\n',
  published: '2017-01-19T11:00:00.000Z',
  url: 'https://media.devchat.tv/my-js-story/JSJ_001.mp3',
  mediaType: '0',
  likes: 0,
  __v: 0,
}];

export default {
  autoPlay: false,
  playlist,
  recent: true,
  liked: false,
  error: null,
};
